//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMapApp {
	
	
	public partial class MasterPage {
		
		protected System.Web.UI.WebControls.TreeView TreeView1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
		
		protected System.Web.UI.WebControls.SiteMapDataSource SiteMapDataSource1;
	}
}
