//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TextSpace;
		
		protected System.Web.UI.WebControls.Panel Pan1;
		
		protected System.Web.UI.WebControls.Panel Pan2;
		
		protected System.Web.UI.WebControls.Panel Pan3;
		
		protected System.Web.UI.WebControls.Label Lable1;
		
		protected System.Web.UI.WebControls.Label Lable2;
		
		protected System.Web.UI.WebControls.TextBox Input1;
		
		protected System.Web.UI.WebControls.TextBox Input2;
		
		protected System.Web.UI.WebControls.TextBox Input3;
		
		protected System.Web.UI.WebControls.TextBox Input4;
		
		protected System.Web.UI.WebControls.TextBox Input5;
		
		protected System.Web.UI.WebControls.Label Line1;
		
		protected System.Web.UI.WebControls.Label Line2;
		
		protected System.Web.UI.WebControls.Label Line3;
		
		protected System.Web.UI.WebControls.Label Line4;
		
		protected System.Web.UI.WebControls.Label Line5;
		
		protected System.Web.UI.WebControls.Button GoButton;
	}
}
