//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlApp {
	
	
	public partial class maketable {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtRows;
		
		protected System.Web.UI.WebControls.TextBox txtCols;
		
		protected System.Web.UI.WebControls.CheckBox chkBorder;
		
		protected System.Web.UI.WebControls.Button cmdMake;
		
		protected System.Web.UI.WebControls.Table tbl;
	}
}
