//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlApp {
	
	
	public partial class ShowListControls {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.CheckBoxList chklst;
		
		protected System.Web.UI.WebControls.Button cmdOK;
		
		protected System.Web.UI.WebControls.Label lblResult;
		
		protected System.Web.UI.WebControls.BulletedList bltLst;
		
		protected System.Web.UI.WebControls.Label lblShowStyle;
	}
}
