//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter {
	
	
	public partial class converter {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText US;
		
		protected System.Web.UI.HtmlControls.HtmlSelect Currency;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton Convert;
		
		protected System.Web.UI.HtmlControls.HtmlInputButton ShowGraph;
		
		protected System.Web.UI.HtmlControls.HtmlImage Graph;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Result;
	}
}
